#
# Travis defaults to building on Ubuntu Precise. We need Trusty
# in order to get up to date versions of cmake and g++
#
language: cpp
sudo: required
dist: trusty

#
# The source is automatically checked out in $TRAVIS_BUILD_DIR
#
before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - cd asplib && mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../install

script: make
